export const LOAD_RECORDS_START = "LOAD_RECORDS_START";
export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";
export const LOAD_RECORDS_ERROR = "LOAD_RECORDS_ERROR";
export const ADD_RECORDS = "ADD_RECORDS";

export const UPDATE_RECORDS = "UPDATE_RECORDS";
